on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        working-directory: ./languages/typescript
        run: npm install
      - name: Run tests
        working-directory: ./languages/typescript
        run: npm test
      - name: Run build
        working-directory: ./languages/typescript
        run: npm run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: ./languages/typescript
          token: ${{ secrets.NPM_TOKEN }}
